### ISSUE TITLE
Cannot locate .exe?

### ISSUE THREAD

**Issue by DeRpMeister** [Zoobumafu/Playlist-Saber#3]
When I open the program, it asks me to locate the Beat Saber folder. So when I do, the program tells me that the folder is wrong, and not the one containing beatsaber.exe even though its the steam one. Is there another .exe I'm missing or is the not being read correctly?

**Comment by Zoobumafu** [comment]
That is weird,
When you pick a directory, the only check up it does is to see if you have Beat Saber.exe (with space), so even if you place an empty file, name Beat Saber.exe on your desktop, and point the program there, it should proceed (and than crash because there is nothing there).

If you have installed the game on the default steam directory, it should be this path - 
C:\Program Files (x86)\Steam\steamapps\common\Beat Saber

If so, I have no idea what is causing the issue honestly, 
is this a shared computer? if so, it might be permissions prevent you from reading the directory..

**Comment by Zoobumafu** [comment]
Hey @DeRpMeister, since we last talk I have released a new version, in which the software instead of trying to detect the install location every launch, it tries to use the last location you used before you exited the software last time, it may solve it for you.

Please let me know how it goes.

**Comment by DeRpMeister** [comment]
The thing is my comment was written when I first downloaded the program for the first time, so I don't think that really did anything for me at least. I have tried with an empty .exe and the program did respond. For some reason it just does not work with the actual Beat Saber folder and .exe.

**Comment by Zoobumafu** [comment]
It really sucks,
I have no idea how to check where the issue might come from without taking at look at your pc/file system tree.

I have noticed few weeks ago with a friend who had an issue where he opens the software and nothing at all happens, we have found out that there was some error in reading one of the songs, which led the software to crash.

To fix it I added a try catch block, so the software just ignores songs who cause errors, it fixed it for him, but if you are already using the latest version it can't be the case.

Another thing I can think of is that you might don't have beta .net 5.0, the software relies on it (sorry, should have used 3.1, but that ship has already passed), you can download it from here - 
https://dotnet.microsoft.com/download/dotnet/5.0

(You need the desktop runtime, it is in the middle right)

**Comment by vejvarm** [comment]
Hi. Having the same issue. I tried it with and without the .NET runtime to no avail. Any updates on this issue?

**Comment by Zoobumafu** [comment]
@vejvarm Hey, I see the message now,
I am on testing session in college, so I can't invest time to check and update the software these days,

If you can let me know what version of BeatSaber you are running, and if BeatSaber is installed on the default location or not I will run some tests when I again have some time (in 2-3 weeks)

**Comment by ranmd9a** [comment]
https://github.com/Zoobumafu/Playlist-Saber/blob/4f80e593853c76bad3f9042762d55b9be2c4a2ee/BeatSaber%20Playlist%20Master%20V2/Methods.cs#L106

Beatsaber.exe
-> Beat saber.exe

**Comment by Zoobumafu** [comment]
@ranmd9a Thanks allot for pointing me to the right spot, I have added a bracket to check both if the name with the space or without exist.

But I think it was not the issue, what I found is that Beat**s**aber.exe is not equal to Beat**S**aber.exe, I have moved my installation folder to another directory and tested, and this seems to fix it.
[PlaylistSaber.zip](https://github.com/Zoobumafu/Playlist-Saber/files/7868364/PlaylistSaber.zip)


@vejvarm @DeRpMeister Can you let me know if the version attached here works for you?
(Had to add it to a zip so GitHub lets me upload it here)

**Comment by vejvarm** [comment]
> @ranmd9a Thanks allot for pointing me to the right spot, I have added a bracket to check both if the name with the space or without exist.
> 
> But I think it was not the issue, what I found is that Beat**s**aber.exe is not equal to Beat**S**aber.exe, I have moved my installation folder to another directory and tested, and this seems to fix it.
> 
> @vejvarm @DeRpMeister Can you let me know if the version attached here works for you? (Had to add it to a zip so GitHub lets me upload it here, unzipped version has been uploaded to Release page) [PlaylistSaber.zip](https://github.com/Zoobumafu/Playlist-Saber/files/7868477/PlaylistSaber.zip)

That fixed it for me! Many thanks and good luck with your exams!

**Comment by Zoobumafu** [comment]
Thank you!!
Glad it's working.
