### ISSUE TITLE
Cant install, .NET Core

### ISSUE THREAD

**Issue by Morgolf** [Zoobumafu/Playlist-Saber#4]
When I try to install it, it says I need a newer version of .NET Core, after grabbing it from the website the error links to, it still doesn't work.

**Comment by Zoobumafu** [comment]
The software uses .net 5.0 which is currently in beta, you are probably redirected to the stable versions of ,net,

You should attempt to install the version found here -
https://dotnet.microsoft.com/download/dotnet/5.0
(You need the .net desktop runtime, it is in the middle right)

(I am closing the issue, but you can reopen it if it doesn't solve it for you)
